blank_issues_enabled: true
contact_links:
  - name: Bug report
    url: https://github.com/camunda/camunda/issues/new/choose
    about: Please report issues in the Camunda issue tracker as "FEEL Bug Report".
  - name: Feature request
    url: https://github.com/camunda/camunda/issues/new/choose
    about: Please suggest enhancements/ideas in the Camunda issue tracker as "FEEL Feature request".
  - name: Documentation
    url: https://github.com/camunda/camunda-docs/issues/new/choose
    about: Please report any missing or incorrect documentation in the Camunda Docs issue tracker.
